name: Build TripiFy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app

      - name: Build with xcodebuild
        run: |
          xcodebuild -project TripiFy.xcodeproj \
                     -scheme TripiFy \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 14' \
                     clean build